// Where each Branding field surfaces in the brand book — powers the field-label → guide links.
// Only fields that feed VISIBLE on-page content are listed; export-only fields (voice.md, JSON,
// formats.json…) get no link so a click never lands where the edit doesn't show.
// Section ids are the book's own <section id="…"> anchors (see docs/mapa-guia-admin.md).
const ANCHORS: Record<string, string> = {
  // 01-strategic
  'bf-purpose': '01-strategic.html#mission',
  'bf-vision': '01-strategic.html#mission',
  'bf-mission': '01-strategic.html#mission',
  'bf-values': '01-strategic.html#mission',
  'bf-story': '01-strategic.html#story',
  'bf-milestones': '01-strategic.html#story',
  'ps-statement': '01-strategic.html#positioning',
  'ps-diff': '01-strategic.html#positioning',
  'ps-uvp': '01-strategic.html#value-prop',
  'bf-promise': '01-strategic.html#value-prop',
  'ap-aaname': '01-strategic.html#audience',
  'ap-aatext': '01-strategic.html#audience',
  'ap-personas': '01-strategic.html#audience',
  'bp-traits': '01-strategic.html#personality',
  'bp-archetype': '01-strategic.html#personality',
  'bp-archetype-desc': '01-strategic.html#personality',
  // 02-voice
  'vt-voicedef': '02-voice.html#voice-tone',
  'vt-tonedef': '02-voice.html#voice-tone',
  'vt-tone-traits': '02-voice.html#writing-principles',
  'vt-grammar': '02-voice.html#grammar',
  'vt-example-on': '02-voice.html#examples',
  'vt-example-off': '02-voice.html#examples',
  'msg-hierarchy': '02-voice.html#messaging',
  'msg-core': '02-voice.html#naming',
  'msg-cta': '02-voice.html#naming',
  'fmt-locales': '02-voice.html#formats',
  'fmt-date': '02-voice.html#formats',
  'fmt-time': '02-voice.html#formats',
  'fmt-currency': '02-voice.html#formats',
  'fmt-storage': '02-voice.html#formats',
  // 03-visual
  'logo-svg': '03-visual.html#logo',
  'logo-primary': '03-visual.html#logo',
  'logo-stacked': '03-visual.html#logo',
  'logo-wordmark': '03-visual.html#logo',
  'logo-mono': '03-visual.html#logo',
  'logo-inverse': '03-visual.html#logo',
  'logo-clearspace': '03-visual.html#logo-usage',
  'logo-minsize': '03-visual.html#logo-usage',
  'logo-primary-clearspace': '03-visual.html#logo-usage',
  'logo-primary-minsize': '03-visual.html#logo-usage',
  'logo-backgrounds': '03-visual.html#logo-usage',
  'logo-bg-photo': '03-visual.html#logo-usage',
  'logo-file-png': '03-visual.html#logo-usage',
  'logo-file-eps': '03-visual.html#logo-usage',
  'logo-file-pdf': '03-visual.html#logo-usage',
  'cd-direction': '03-visual.html#color',
  'cd-brand-hex': '03-visual.html#color',
  'cd-palette': '03-visual.html#color',
  'cd-dark': '03-visual.html#color',
  'cd-contrast': '03-visual.html#darkmode',
  'dm-accent': '03-visual.html#darkmode',
  'dm-surface': '03-visual.html#darkmode',
  'td-direction': '03-visual.html#typography',
  'td-personality': '03-visual.html#typography',
  'font-display': '03-visual.html#typography',
  'font-text': '03-visual.html#typography',
  'font-mono': '03-visual.html#typography',
  'font-extra': '03-visual.html#typography',
  'vi-grid': '03-visual.html#grid',
  'grid-columns': '03-visual.html#grid',
  'grid-spacing': '03-visual.html#grid',
  'img-style': '03-visual.html#imagery',
  'img-treatment': '03-visual.html#imagery',
  'img-photo': '03-visual.html#imagery',
  'img-photo-2': '03-visual.html#imagery',
  'img-photo-3': '03-visual.html#imagery',
  'ill-style': '03-visual.html#illustration',
  'ill-ref-1': '03-visual.html#illustration',
  'ill-ref-2': '03-visual.html#illustration',
  'ill-ref-3': '03-visual.html#illustration',
  'ge-style': '03-visual.html#graphic-elements',
  'ge-ref-1': '03-visual.html#graphic-elements',
  'ge-ref-2': '03-visual.html#graphic-elements',
  'ge-ref-3': '03-visual.html#graphic-elements',
  'cd-print': '03-visual.html#color',
  'app-rules': '04-applications.html#main',
  'print-pieces': '04-applications.html#print',
  'dig-og': '04-applications.html#digital',
  'appicon-ios': '04-applications.html#app-icons',
  'appicon-android': '04-applications.html#app-icons',
  'appicon-play': '04-applications.html#app-icons',
  'social-networks': '04-applications.html#social',
  'sig-phone': '04-applications.html#email',
  'pres-pieces': '04-applications.html#presentations',
  'pack-pieces': '04-applications.html#packaging',
  'sign-pieces': '04-applications.html#signage',
  'env-pieces': '04-applications.html#environmental',
  'merch-pieces': '04-applications.html#merch',
  'veh-pieces': '04-applications.html#vehicle',
  // Slots de imagen de 04: mismos conteos que el catálogo de piezas (seeds `slots()` en branding.ts).
  ...Object.fromEntries(
    (
      [
        ['print', 6, 'print'],
        ['social', 6, 'social'],
        ['pres', 5, 'presentations'],
        ['pack', 5, 'packaging'],
        ['sign', 5, 'signage'],
        ['env', 5, 'environmental'],
        ['merch', 6, 'merch'],
        ['veh', 4, 'vehicle'],
      ] as const
    ).flatMap(([pre, n, anchor]) =>
      Array.from({ length: n }, (_, i) => [`${pre}-img-${i + 1}`, `04-applications.html#${anchor}`]),
    ),
  ),
  'ico-provider': '03-visual.html#iconography',
  'ico-style': '03-visual.html#iconography',
  'mo-personality': '03-visual.html#motion',
  'mo-duration': '03-visual.html#motion',
  'mo-easing': '03-visual.html#motion',
  'dv-style': '03-visual.html#dataviz',
  'sonic-style': '03-visual.html#sonic',
  'sonic-clip-1': '03-visual.html#sonic',
  'sonic-clip-2': '03-visual.html#sonic',
  'sonic-clip-3': '03-visual.html#sonic',
  'acc-req': '03-visual.html#accessibility',
  // 05-resources
  'legal-entity': '05-resources.html#legal',
  'legal-tm': '05-resources.html#legal',
  'legal-notice': '05-resources.html#legal',
  'gov-review': '05-resources.html#governance',
  'ver-log': '05-resources.html#versioning',
  'apr': '05-resources.html#versioning',
  'gov-owner': '05-resources.html#governance',
  'gov-contact': '05-resources.html#governance',
  'gov-approvals': '05-resources.html#governance',
}

// Deep link into the brand book for a field, or null when the field has no visible guide slot.
export function bookFieldHref(fieldId: string, workspaceId: string): string | null {
  const target = ANCHORS[fieldId]
  if (!target) return null
  const [page, hash] = target.split('#')
  return `/book/${page}?brand=${encodeURIComponent(workspaceId)}#${hash}`
}
